### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by scythetleppo** [blizzhackers/pickits#17]
![image](https://github.com/blizzhackers/pickits/assets/99230615/04cdd45a-86ca-437a-99c6-fe2a83317a04)
Any chance to update?

**Comment by laztheripper** [comment]
Hey,

It already didn't work on pickits only a year or two after NipCheck was released by Noah because of new aliases and pickit syntax added. It not longer being compatible with recent N++ versions only makes it official.

Unfortunately I don't believe it will be updated. If anyone wants to pick this up, it would be trivial to implement something similar in VSCode for example, and be easier to extend and update independently.

If someone wants to do that, let me know. Otherwise I think this issue can be closed, sorry!
